services:
  # NestJS API
  - type: web
    name: chms-api
    runtime: node
    region: oregon
    plan: free
    branch: develop
    buildCommand: npm ci && npm run build
    startCommand: node dist/main.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      # Ensure devDependencies are installed during build
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: chms-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 1h
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRATION
        value: 7d
      - key: API_PREFIX
        value: api/v1

databases:
  - name: chms-postgres
    plan: free
    region: oregon
